### PR TITLE
added optinal pca and optinal iteration

### PR DESCRIPTION
**Pull request by Stealeristaken**
I have added the optional execution of the PCA process and the ability to specify the number of iterations as an integer.

### CODE REVIEW

**Comment by cobanov** [comment]
Actually, I think it makes more sense to open a pull request for each change, let's not change more than one thing at the same time.

The change you made for kmeans definitely looks very useful and I find it logical.

The vector length of the model output is really long, yes, you kept it optional, but in any case, I think it makes sense to keep PCA, running Kmeans without reducing the size does not make much sense to me.

**Comment by Stealeristaken** [comment]
I opened this pr all at once because the changes were small imo. x) 

Yes, you are right. In many cases, it doesn't make sense to not perform PCA. But, as you said, I kept it optional by setting the default to True. However, you are the boss, so if you want me to change it, please create a comment on the code line, and I will do it ASAP

**Comment by cobanov** [comment]
No worries! It's good, thank you for your contribution!

**Comment by cobanov** [comment]
https://github.com/cobanov/tasnif/releases/tag/0.1.10

**Pull request merged**
