### PR TITLE
A logger file has been added for log management.

### PR DESCRIPTION
**Pull request by sinanerdinc**
I made an addition so that log management can be handled from a single place instead of configuring it separately in each file.

### CODE REVIEW

**Comment by cobanov** [comment]
This is really a much better option, in fact, after you made the changes in rich, I realized that we were actually printing the time and level twice, do you think such a solution would make more sense? 

let's remove it from the log template and activate it from rich.

```python
log_format = "%(message)s"
logging.basicConfig(
    level="INFO", format=log_format, datefmt="[%X]", handlers=[RichHandler(show_time=True, show_level=True)]
)
`

**Comment by sinanerdinc** [comment]
The only issue with using RichHandler is that if two logs arrive simultaneously, only one date will be written. You can check the output in the terminal by running logger.py

image


If we disable RichHandler and use it via the template, it would work like this.
image

**Comment by cobanov** [comment]
Hmm, I see. Make sense then, thank you Sinan, it's perfect!

**Comment by cobanov** [comment]
https://github.com/cobanov/tasnif/releases/tag/0.1.10

**Pull request merged**
